---
meta:
  name:    doomsday
  target:  doomsday@pipes
  url:     https://pipes.starkandwayne.com

  test-errand: ~

  initial_version: 1.0.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  bosh-lite:
    target:   https://10.200.131.9:25555
    cacert:   ((thunder-dome.ca-certificate))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((cfcommunity.access))
    secret_key:  ((cfcommunity.secret))

  github:
    owner:  doomsday-project
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github.private-key))
    username:  ((github.username))
    access_token: ((github.access-token))

  slack:
    webhook:       ((slack.webhook))
    username:      doomsday-bot
    icon:          'http://www.iconarchive.com/download/i99480/webalys/kameleon.pics/Nuclear-Mushroom.ico'
    channel:       '#botspam'
    blob_success:  '(( concat ": New version of  was detected, and updated in master. <" meta.url "/teams//pipelines/| Cut a new release?>" ))'
    blob_failure:  '(( concat ": :airplane_arriving: <" meta.url "/teams//pipelines//jobs//builds/| Failed to update the blob for >" ))'


groups:
- name: blobs
  jobs:
  - doomsday

jobs:
- name: doomsday
  public: true
  plan:
  - aggregate:
    - get: git
    - get: doomsday
      trigger: true
      params:
        globs: [doomsday-linux]
  - task: update-doomsday
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: (( grab meta.image.name ))
          tag:        (( grab meta.image.tag ))
      inputs:
      - name: git
      - name: doomsday
      outputs:
      - name: pushme
      run:
        path: ./git/ci/scripts/update-blob
      params:
        REPO_ROOT:   git
        REPO_OUT:    pushme
        BLOB_DIR:    doomsday
        BLOB_NAME:   doomsday
        BLOB_BINARY: doomsday-linux
        BLOB_DESTINATION: doomsday/doomsday
        BLOB_CLEANUP:     doomsday/doomsday
        AWS_ACCESS_KEY: (( grab meta.aws.access_key ))
        AWS_SECRET_KEY: (( grab meta.aws.secret_key ))
        BRANCH:         (( grab meta.github.branch ))

  - put: git
    params:
      rebase: true
      repository: pushme/git


resources:
- name: doomsday
  type: github-release
  source:
    user: doomsday-project
    repository: doomsday
    access_token: (( grab meta.github.access_token ))
